### ISSUE TITLE
Renaming of `Deployment` to `Workflow Run` in the title of the slack message

### ISSUE THREAD

**Issue by DmitryMihailov** [crederauk/slack-workflow-summary#133]
Small proposal: renaming of `Deployment` to `Workflow Run` in the title of the end slack message. I think it makes more sense as then slack message doesn't look that confusing for many other use cases - for example I'm using this for testing and `Deployment` in slack title bothers me _a bit_ 😅

**Proposed PR:** #132

**Comment by lewis-od** [comment]
Implemented in #132
